import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./(components)/Providers";
import { Nav } from '@/app/(components)/Nav'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bet NBA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <Providers>
      <main className={"dark text-foreground bg-background"}>
        <Nav />
        {children}
      </main>
    </Providers>
    </body>
    </html>
  );
}
